language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

matrix:
  allow_failures:
    - python: "3.7-dev"

install:
    - "pip install -r requirements-build.txt"
    - "pip install --process-dependency-links --editable ."

script:
    - "pycodestyle"
    - "pytest tests/"

cache:
    apt: true
    pip: true
