language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

# Matrix approach here due to: https://github.com/travis-ci/travis-ci/issues/9815
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
          install:
              - "pip install cython"
              - "pip install -r requirements-build.txt"
              - "pip install --process-dependency-links --editable ."

install:
    - "pip install -r requirements-build.txt"
    - "pip install --process-dependency-links --editable ."

script:
    - "pycodestyle"
    - "pytest tests/"

cache:
    apt: true
    pip: true
